=== ericquartey/wms/VerticalWarehouses/Panel PC UI/Ferretto.VW.App.Controls/Controls/Keyboards/Demo/KeyboardLayout.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.w3schools.com"
xmlns="http://www.w3schools.com"
elementFormDefault="qualified">

  <xs:simpleType name="KeySendModeType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Char" />
      <xs:enumeration value="KeyDown" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ModifiersType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Alt" />
      <xs:enumeration value="Shift" />
      <xs:enumeration value="Ctrl" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TextEnteringModeType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Insert" />
      <xs:enumeration value="Overtype" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="InputControlType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="TextBox" />
      <xs:enumeration value="NumericUpDown" />
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="KeyboardDefinition">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="KeyboardLayout" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Row" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Key" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute type="xs:string" name="Value" />
                        <xs:attribute type="xs:string" name="ShiftValue" />
                        <xs:attribute type="xs:string" name="AltValue" />
                        <xs:attribute type="xs:string" name="ShiftAltValue" />
                        <xs:attribute type="xs:string" name="FuncValue" />
                        <xs:attribute type="xs:string" name="Text" />
                        <xs:attribute type="xs:string" name="ShiftText" />
                        <xs:attribute type="xs:string" name="AltText" />
                        <xs:attribute type="xs:string" name="ShiftAltText" />
                        <xs:attribute type="xs:string" name="FuncText" />
                        <xs:attribute type="KeySendModeType" name="SendAs" />
                        <xs:attribute type="xs:string" name="SetLayout"  />
                        <xs:attribute type="xs:boolean" name="Toggle" />
                        <xs:attribute type="xs:boolean" name="AutoRollback" />
                        <xs:attribute type="xs:boolean" name="Checked" />
                        <xs:attribute type="xs:boolean" name="UseModifiers" />
                        <xs:attribute type="xs:string" name="Width" />
                        <xs:attribute type="xs:string" name="Height" />
                        <xs:attribute type="xs:integer" name="LeftMargin" />
                        <xs:attribute type="xs:integer" name="RowSpan" />
                        <xs:attribute type="xs:integer" name="ColSpan" />
                        <xs:attribute type="xs:integer" name="Offset" />
                        <xs:attribute type="ModifiersType" name="Modifiers" />
                        <xs:attribute type="xs:string" name="StyleSelector" />
                        <xs:attribute type="xs:string" name="Action" />
                        <xs:attribute type="xs:boolean" name="LayoutSelector" />
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="LayoutSelector" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute type="xs:string" name="Text" />
                        <xs:attribute type="xs:string" name="StyleSelector" />
                        <xs:attribute type="xs:string" name="Width" />
                        <xs:attribute type="xs:string" name="Height" />
                        <xs:attribute type="xs:integer" name="LeftMargin" />
                        <xs:attribute type="xs:integer" name="RowSpan" />
                        <xs:attribute type="xs:integer" name="ColSpan" />
                        <xs:attribute type="xs:integer" name="Offset" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:integer" name="LeftMargin"  />
                  <xs:attribute type="xs:integer" name="KeyWidth" />
                  <xs:attribute type="xs:integer" name="KeyHeight" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="Id" use="required" />
            <xs:attribute type="xs:string" name="KeyStyleSelector" />
            <xs:attribute type="xs:integer" name="Width" />
            <xs:attribute type="xs:integer" name="Height" />
            <xs:attribute type="xs:integer" name="KeyWidth" />
            <xs:attribute type="xs:integer" name="KeyHeight"  />
            <xs:attribute type="xs:integer" name="RowPadding" />
            <xs:attribute type="xs:integer" name="KeyPadding" />
            <xs:attribute type="xs:integer" name="RowLeftMargin" />
            <xs:attribute type="xs:string" name="LoadAction" />
            <xs:attribute type="TextEnteringModeType" name="TextEnteringMode" />
            <xs:attribute type="xs:boolean" name="ClearOnFirstDigit" />
            <xs:attribute type="InputControlType" name="InputControlType" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="xs:string" name="ActiveLayout" />
    </xs:complexType>

    <xs:unique name="UniqueName">
      <xs:selector xpath="class" />
      <xs:field xpath="@Name" />
    </xs:unique>

  </xs:element>
</xs:schema>

=== ericquartey/wms/VerticalWarehouses/Panel PC UI/Ferretto.VW.App.Controls/Controls/Keyboards/Demo/ru_RU.xml
<?xml version="1.0" encoding="utf-8" ?>

<KeyboardDefinition
  xmlns="http://www.w3schools.com"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.w3schools.com KeyboardLayout.xsd"

  ActiveLayout="Querty">

  <!-- Default complete qwerty layout without numpad -->
  <KeyboardLayout Id="Querty"
                  Width="790"
                  Height="485"
                  KeyWidth="51"
                  KeyHeight="51"
                  RowPadding="0"
                  KeyPadding="0"
                  RowLeftMargin="6">

    <Row>
      <Key Text="ESC" Action="EndEdit" StyleSelector="highlight" />
      <Key Value="ё" ShiftValue="Ё" />
      <Key Value="1" ShiftValue="!" />
      <Key Value="2" ShiftValue="&quot;" />
      <Key Value="3" ShiftValue="№" />
      <Key Value="4" ShiftValue=";" />
      <Key Value="5" ShiftValue="%" />
      <Key Value="6" ShiftValue=":" />
      <Key Value="7" ShiftValue="?" />
      <Key Value="8" ShiftValue="*" AltValue="₽" />
      <Key Value="9" ShiftValue="(" />
      <Key Value="0" ShiftValue=")" />
      <Key Value="-" ShiftValue="_" />
      <Key Text="Canc" Action="Clear" Width="93" StyleSelector="highlight" />
    </Row>
    <Row LeftMargin="77">
      <Key Value="й" ShiftValue="Й" AltValue="Q" />
      <Key Value="ц" ShiftValue="Ц" AltValue="W" />
      <Key Value="у" ShiftValue="У" AltValue="E" />
      <Key Value="к" ShiftValue="К" AltValue="R" />
      <Key Value="е" ShiftValue="Е" AltValue="T" />
      <Key Value="н" ShiftValue="Н" AltValue="Y" />
      <Key Value="г" ShiftValue="Г" AltValue="U" />
      <Key Value="ш" ShiftValue="Ш" AltValue="I" />
      <Key Value="щ" ShiftValue="Щ" AltValue="O" />
      <Key Value="з" ShiftValue="З" AltValue="P" />
      <Key Value="х" ShiftValue="Х" AltValue="[" ShiftAltValue="{" />
      <Key Value="ъ" ShiftValue="Ъ" AltValue="]" ShiftAltValue="}" />
      <Key Text="" Value="\d8" SendAs="KeyDown" Width="73" StyleSelector="highlight backspace-key" />
    </Row>
    <Row>
      <Key Text="Caps Lock" Modifiers="Shift" Toggle="true" Width="82" StyleSelector="highlight capslock-key" />
      <Key Value="ф" ShiftValue="Ф" AltValue="A" />
      <Key Value="ы" ShiftValue="Ы" AltValue="S" />
      <Key Value="в" ShiftValue="В" AltValue="D" />
      <Key Value="а" ShiftValue="А" AltValue="F" />
      <Key Value="п" ShiftValue="П" AltValue="G" />
      <Key Value="р" ShiftValue="Р" AltValue="H" />
      <Key Value="о" ShiftValue="О" AltValue="J" />
      <Key Value="л" ShiftValue="Л" AltValue="K" />
      <Key Value="д" ShiftValue="Д" AltValue="L" />
      <Key Value="ж" ShiftValue="Ж" AltValue=":" ShiftAltValue=";" />
      <Key Value="э" ShiftValue="Э" AltValue="'" ShiftAltValue="&quot;" />
      <Key Value="\" ShiftValue="/" />
      <Key Text="Enter" Action="Accept" Width="62" RowSpan="2" StyleSelector="highlight enter-key" />
    </Row>
    <Row>
      <Key Text="Shift" Modifiers="Shift" Toggle="true" AutoRollback="true" Width="56" StyleSelector="highlight" />
      <Key Value="\" ShiftValue="/" />
      <Key Value="я" ShiftValue="Я" AltValue="Z" />
      <Key Value="ч" ShiftValue="Ч" AltValue="X" />
      <Key Value="с" ShiftValue="С" AltValue="C" />
      <Key Value="м" ShiftValue="М" AltValue="V" />
      <Key Value="и" ShiftValue="И" AltValue="B" />
      <Key Value="т" ShiftValue="Т" AltValue="N" />
      <Key Value="ь" ShiftValue="Ь" AltValue="M" />
      <Key Value="б" ShiftValue="Б" />
      <Key Value="ю" ShiftValue="Ю" AltValue=";" />
      <Key Value="." ShiftValue="," AltValue=":" />
      <Key Value="=" ShiftValue="+" />
    </Row>
    <Row>
      <Key Text="Alt" Modifiers="Alt" Toggle="true" AutoRollback="true" Width="56" StyleSelector="highlight" />
      <Key Text="&amp;123" SetLayout="SymbolsNumpad" ColSpan="2" StyleSelector="highlight2" />
      <Key Text="" Value="\d32" ColSpan="9" />
      <Key LayoutSelector="true" Text="Russo" Width="139" StyleSelector="key-lang" />
    </Row>
  </KeyboardLayout>

  <!-- This layout contains symbols and numbers and is meant to be used when user
  need input a lot of number or symbols in an easy way -->
  <KeyboardLayout Id="SymbolsNumpad"
                  Width="790"
                  Height="485"
                  KeyWidth="51"
                  KeyHeight="51"
                  RowPadding="0"
                  KeyPadding="0"
                  RowLeftMargin="6" >

    <Row>
      <!-- Symbols -->
      <Key Text="ESC" Width="65" Action="EndEdit" StyleSelector="highlight" />
      <Key Value="!" />
      <Key Value="?" />
      <Key Value="@" />
      <Key Value="#" />
      <Key Value="$" />
      <Key Value="%" />
      <Key Value="/" />

      <!-- Numpad -->
      <Key Value="*" Offset="2" Width="60" LeftMargin="-8" />
      <Key Value="-" Width="60" />
      <Key Text="" Value="\d8" SendAs="KeyDown" Width="60" StyleSelector="highlight backspace-key" />
      <Key Text="Canc" Action="Clear" Width="60" StyleSelector="highlight" />
    </Row>
    <Row>
      <!-- Symbols -->
      <Key Value="&amp;" />
      <Key Value="£" />
      <Key Value="~" />
      <Key Value="_" />
      <Key Value="\" />
      <Key Value="{" />
      <Key Value="}" />
      <Key Text="Enter" Value="\d13" Action="Accept" RowSpan="3" Width="65" StyleSelector="highlight enter-key" />

      <!-- Numpad -->
      <Key Value="7" Offset="2" Width="60" LeftMargin="-8" />
      <Key Value="8" Width="60" />
      <Key Value="9" Width="60" />
      <Key Value="+" RowSpan="2" Width="60" />
    </Row>
    <Row>
      <!-- Symbols -->
      <Key Value=":" />
      <Key Value="&quot;" />
      <Key Value="ì" />
      <Key Value="(" />
      <Key Value=")" />
      <Key Value="[" />
      <Key Value="]" />

      <!-- Numpad -->
      <Key Value="4" LeftMargin="6" Offset="3" Width="60" />
      <Key Value="5" Width="60" />
      <Key Value="6" Width="60" />
    </Row>
    <Row>
      <!-- Symbols -->
      <Key Value="." />
      <Key Value="," />
      <Key Value=";" />
      <Key Value="&lt;" />
      <Key Value="&gt;" />
      <Key Value="¥" />
      <Key Value="|" />

      <!-- Numpad -->
      <Key Value="1" LeftMargin="6" Offset="3" Width="60" />
      <Key Value="2" Width="60" />
      <Key Value="3" Width="60" />
      <Key Text="Enter" Action="Accept" RowSpan="2" StyleSelector="highlight enter-key" Width="60" />
    </Row>
    <Row>
      <!-- Symbols -->
      <Key Text="ABC" SetLayout="Querty" ColSpan="2" StyleSelector="highlight2" />
      <Key Text="" Value="\d32" Width="320" />

      <!-- Numpad -->
      <Key Value="0" ColSpan="2" Offset="2" Width="60" LeftMargin="-8" />
      <Key Value="." Width="60" />
    </Row>

  </KeyboardLayout>

  <!-- This layout contains only numbers and is meant to be used when user
  need input a lot of number in an easy way -->
  <KeyboardLayout Id="Numpad"
                  Width="300"
                  Height="440"
                  KeyWidth="55"
                  KeyHeight="55"
                  RowPadding="2"
                  KeyPadding="2"
                  RowLeftMargin="23"
                  ClearOnFirstDigit="true" >

    <Row>
      <Key Value="7" />
      <Key Value="8" />
      <Key Value="9" />
      <Key Text="ESC" Action="EndEdit" StyleSelector="highlight" />
    </Row>
    <Row>
      <Key Value="4" />
      <Key Value="5" />
      <Key Value="6" />
      <Key Text="" Value="\d8" SendAs="KeyDown" StyleSelector="highlight backspace-key" />
    </Row>
    <Row>
      <Key Value="1" />
      <Key Value="2" />
      <Key Value="3" />
      <Key Action="Accept" RowSpan="2" StyleSelector="highlight enter-key" />
    </Row>
    <Row>
      <Key Value="0" />
      <Key Text="," Action="InsertDecimalSeparator" StyleSelector="highligth" />
      <Key Text="+ / -" Action="ToggleSign" StyleSelector="highligth" />
    </Row>
  </KeyboardLayout>

  <!-- This layout contains only numbers and is meant to be used when user
  need input a lot of number in an easy way -->
  <KeyboardLayout Id="IPAddressInputPanel"
                  Width="353"
                  Height="440"
                  KeyWidth="55"
                  KeyHeight="55"
                  RowPadding="2"
                  KeyPadding="2"
                  RowLeftMargin="23" >

    <Row>
      <Key Text="ESC" Action="EndEdit" StyleSelector="highlight" />
      <Key Text="HOST NAME" SetLayout="Querty" ColSpan="3" StyleSelector="highlight" />
      <Key Action="Back" StyleSelector="highlight backspace-key" />
    </Row>
    <Row>
      <Key Value="1" Action="KeyDown" />
      <Key Value="2" Action="KeyDown" />
      <Key Value="3" Action="KeyDown" />
      <Key Value="4" Action="KeyDown" />
      <Key Text="|__|" Action="BackBlock" StyleSelector="highlight" />
    </Row>
    <Row>
      <Key Value="5" Action="KeyDown" />
      <Key Value="6" Action="KeyDown" />
      <Key Value="7" Action="KeyDown" />
      <Key Value="8" Action="KeyDown" />
      <Key Action="Accept" RowSpan="2" StyleSelector="highlight enter-key" />
    </Row>
    <Row>
      <Key Value="9" Action="KeyDown" />
      <Key Value="0" Action="KeyDown" />
      <Key Value="." Action="KeyDown" ColSpan="2" />
    </Row>
  </KeyboardLayout>

  <KeyboardLayout Id="Boolpad"
                  Width="300"
                  Height="325"
                  KeyWidth="55"
                  KeyHeight="55"
                  RowPadding="2"
                  KeyPadding="2"
                  RowLeftMargin="23"
                  TextEnteringMode="Overtype" >
    <Row>
      <Key Text="1" RowSpan="2" Value="1" />
      <Key Text="0" RowSpan="2" Value="0" />
      <Key Text="" Value="\d8" SendAs="KeyDown" StyleSelector="highlight backspace-key" />
      <Key Text="ESC" Action="EndEdit" StyleSelector="highlight" />
    </Row>
    <Row>
      <Key Action="Accept" Offset="2" LeftMargin="4" ColSpan="2" StyleSelector="highlight enter-key" />
    </Row>
  </KeyboardLayout>

</KeyboardDefinition>
